[plugin]
repository = "https://github.com/FPC-PM/NameplateSignResizer.git"
commit = "b4209226876f88cb5969a623bfad564d9027fceb"
owners = ["FPC-PM"]
project_path = "NameplateSignResizer"
changelog = "Initial Release"